/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HomoeopathyRouteImport } from './routes/homoeopathy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiseasesIndexRouteImport } from './routes/diseases.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DiseasesSlugRouteImport } from './routes/diseases.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HomoeopathyRoute = HomoeopathyRouteImport.update({
  id: '/homoeopathy',
  path: '/homoeopathy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesIndexRoute = DiseasesIndexRouteImport.update({
  id: '/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesSlugRoute = DiseasesSlugRouteImport.update({
  id: '/diseases/$slug',
  path: '/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/homoeopathy': typeof HomoeopathyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diseases/': typeof DiseasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/homoeopathy': typeof HomoeopathyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/diseases': typeof DiseasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/homoeopathy': typeof HomoeopathyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/diseases/': typeof DiseasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/homoeopathy'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diseases/$slug'
    | '/blog/'
    | '/diseases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/homoeopathy'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diseases/$slug'
    | '/blog'
    | '/diseases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/homoeopathy'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/diseases/$slug'
    | '/blog/'
    | '/diseases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomoeopathyRoute: typeof HomoeopathyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DiseasesSlugRoute: typeof DiseasesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DiseasesIndexRoute: typeof DiseasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homoeopathy': {
      id: '/homoeopathy'
      path: '/homoeopathy'
      fullPath: '/homoeopathy'
      preLoaderRoute: typeof HomoeopathyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/': {
      id: '/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/$slug': {
      id: '/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof DiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomoeopathyRoute: HomoeopathyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  DiseasesSlugRoute: DiseasesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DiseasesIndexRoute: DiseasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
